-- SQL Query to Insert Users in dbo.Users.

INSERT INTO dbo.Users VALUES (10001, 'Daleen', 'du Plessis', 'Architect', 'San Francisco')
INSERT INTO dbo.Users VALUES (10002, 'Ben', 'van Zyl', 'Doctor', 'Seattle')
INSERT INTO dbo.Users VALUES (10003, 'Chris', 'Groenewald', 'Engineer', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10004, 'Jannie', 'du Toit', 'Teacher', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10005, 'Helena', 'Botha', 'Manager', 'Tacoma')
INSERT INTO dbo.Users VALUES (10006, 'Hester', 'de Villiers', 'Plumber', 'San Francisco')
INSERT INTO dbo.Users VALUES (10007, 'Tiaan', 'Theron', 'Electrician', 'Seattle')
INSERT INTO dbo.Users VALUES (10008, 'Dirk', 'Fourie', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10009, 'Annemarie', 'de Kock', 'Doctor', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10010, 'Louis', 'de Wet', 'Engineer', 'Seattle')
INSERT INTO dbo.Users VALUES (10011, 'Susan', 'Kemp', 'Teacher', 'Portland')
INSERT INTO dbo.Users VALUES (10012, 'Koos', 'Kriel', 'Architect', 'Irvine')
INSERT INTO dbo.Users VALUES (10013, 'Irene', 'van der Merwe', 'Doctor', 'Portland')
INSERT INTO dbo.Users VALUES (10014, 'Yvonne', 'Dippenaar', 'Engineer', 'Irvine')
INSERT INTO dbo.Users VALUES (10015, 'Juan', 'le Roux', 'Teacher', 'Seattle')
INSERT INTO dbo.Users VALUES (10016, 'Wilna', 'Rossouw', 'Architect', 'Seattle')
INSERT INTO dbo.Users VALUES (10017, 'Estie', 'Liebenberg', 'Doctor', 'San Diego')
INSERT INTO dbo.Users VALUES (10018, 'Christelle', 'van Zyl', 'Engineer', 'Seattle')
INSERT INTO dbo.Users VALUES (10019, 'Piet', 'Smit', 'Teacher', 'Seattle')
INSERT INTO dbo.Users VALUES (10020, 'Anila', 'Shehu', 'Architect', 'Seattle')
INSERT INTO dbo.Users VALUES (10021, 'Alban', 'Fusha', 'Doctor', 'Tacoma')
INSERT INTO dbo.Users VALUES (10022, 'Altin', 'Mali', 'Engineer', 'San Francisco')
INSERT INTO dbo.Users VALUES (10023, 'Ardit', 'Basha', 'Teacher', 'Seattle')
INSERT INTO dbo.Users VALUES (10024, 'Dritan', 'Kodra', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10025, 'Rovena', 'Vogli', 'Doctor', 'Portland')
INSERT INTO dbo.Users VALUES (10026, 'Fatmir', 'Bregu', 'Engineer', 'Portland')
INSERT INTO dbo.Users VALUES (10027, 'Agron', 'Bardhi', 'Architect', 'Irvine')
INSERT INTO dbo.Users VALUES (10028, 'Anisa', 'Meta', 'Doctor', 'San Diego')
INSERT INTO dbo.Users VALUES (10029, 'Erjona', 'Hasa', 'Engineer', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10030, 'Gentiana', 'Gjoka', 'Teacher', 'Portland')
INSERT INTO dbo.Users VALUES (10031, 'Blerina', 'Hafizi', 'Architect', 'Portland')
INSERT INTO dbo.Users VALUES (10032, 'Ilir', 'Deda', 'Engineer', 'Irvine')
INSERT INTO dbo.Users VALUES (10033, 'Etleva', 'Hysa', 'Electrician', 'Tacoma')
INSERT INTO dbo.Users VALUES (10034, 'Ermal', 'Prifti', 'Architect', 'Portland')
INSERT INTO dbo.Users VALUES (10035, 'Brunilda', 'Kola', 'Doctor', 'Irvine')
INSERT INTO dbo.Users VALUES (10036, 'Fatos', 'Zeneli', 'Engineer', 'San Diego')
INSERT INTO dbo.Users VALUES (10037, 'Elona', 'Leka', 'Teacher', 'Tacoma')
INSERT INTO dbo.Users VALUES (10038, 'Sonila', 'Rama', 'Architect', 'San Francisco')
INSERT INTO dbo.Users VALUES (10039, 'Gentian', 'Pisha', 'Doctor', 'San Francisco')
INSERT INTO dbo.Users VALUES (10040, 'Ameha', 'Mebratu', 'Architect', 'San Francisco')
INSERT INTO dbo.Users VALUES (10041, 'Eba', 'Lencho', 'Doctor', 'San Francisco')
INSERT INTO dbo.Users VALUES (10042, 'Daniel', 'Sebsibe', 'Engineer', 'San Francisco')
INSERT INTO dbo.Users VALUES (10043, 'Hassen', 'Seid', 'Teacher', 'San Diego')
INSERT INTO dbo.Users VALUES (10044, 'Hayat', 'Hassen', 'Manager', 'Tacoma')
INSERT INTO dbo.Users VALUES (10045, 'Gifti', 'Boru', 'Plumber', 'San Francisco')
INSERT INTO dbo.Users VALUES (10046, 'Selam', 'Fekadu', 'Electrician', 'Seattle')
INSERT INTO dbo.Users VALUES (10047, 'Kemiliya', 'Hussien', 'Architect', 'Seattle')
INSERT INTO dbo.Users VALUES (10048, 'Dibora', 'Abebe', 'Doctor', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10049, 'Eden', 'Sisay', 'Engineer', 'Tacoma')
INSERT INTO dbo.Users VALUES (10050, 'Tekola', 'Melaku', 'Teacher', 'Portland')
INSERT INTO dbo.Users VALUES (10051, 'Yohannes', 'Yared', 'Architect', 'Portland')
INSERT INTO dbo.Users VALUES (10052, 'Mikias', 'Alemayehu', 'Doctor', 'Irvine')
INSERT INTO dbo.Users VALUES (10053, 'Gezahegne', 'Mulugeta', 'Engineer', 'San Francisco')
INSERT INTO dbo.Users VALUES (10054, 'Meron', 'Fikremariam', 'Teacher', 'San Francisco')
INSERT INTO dbo.Users VALUES (10055, 'Petros', 'Yaregal', 'Architect', 'San Francisco')
INSERT INTO dbo.Users VALUES (10056, 'Mekdes', 'Solomon', 'Doctor', 'Irvine')
INSERT INTO dbo.Users VALUES (10057, 'Meseret', 'Meles', 'Engineer', 'San Diego')
INSERT INTO dbo.Users VALUES (10058, 'Selhadin', 'Jemal', 'Teacher', 'Seattle')
INSERT INTO dbo.Users VALUES (10059, 'Dabir', 'Al-Zuhairi', 'Architect', 'San Diego')
INSERT INTO dbo.Users VALUES (10060, 'Ataa', 'Badakhshi', 'Doctor', 'Irvine')
INSERT INTO dbo.Users VALUES (10061, 'Radi', 'Bettar', 'Engineer', 'San Francisco')
INSERT INTO dbo.Users VALUES (10062, 'Humayd', 'Wahdani', 'Teacher', 'Seattle')
INSERT INTO dbo.Users VALUES (10063, 'Hamed', 'Bettar', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10064, 'Jakeem', 'Mustafa', 'Doctor', 'Portland')
INSERT INTO dbo.Users VALUES (10065, 'Thaqib', 'Hakimi', 'Engineer', 'San Diego')
INSERT INTO dbo.Users VALUES (10066, 'Basel', 'Karzai', 'Architect', 'Irvine')
INSERT INTO dbo.Users VALUES (10067, 'Homsi', 'Boutros', 'Doctor', 'San Diego')
INSERT INTO dbo.Users VALUES (10068, 'Abdul-Qahhar', 'Abadi', 'Engineer', 'Tacoma')
INSERT INTO dbo.Users VALUES (10069, 'Nabighah', 'Maarouf', 'Teacher', 'San Francisco')
INSERT INTO dbo.Users VALUES (10070, 'Mukhtar', 'Sarraf', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10071, 'Dameer', 'Refai', 'Engineer', 'Seattle')
INSERT INTO dbo.Users VALUES (10072, 'Azeem', 'Ghanem', 'Electrician', 'Seattle')
INSERT INTO dbo.Users VALUES (10073, 'Abadi', 'Maalouf', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10074, 'Aisha', 'Al-Lami', 'Doctor', 'Portland')
INSERT INTO dbo.Users VALUES (10075, 'Lucine', 'Homsi', 'Engineer', 'San Francisco')
INSERT INTO dbo.Users VALUES (10076, 'Kadijah', 'Batlouni', 'Teacher', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10077, 'Alea', 'Natsheh', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10078, 'Jibran', 'Sabbagh', 'Doctor', 'Tacoma')
INSERT INTO dbo.Users VALUES (10079, 'Dharef', 'Sayegh', 'Teacher', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10080, 'Imtiyaz', 'Salman', 'Architect', 'Portland')
INSERT INTO dbo.Users VALUES (10081, 'Rabeh', 'Zaher', 'Architect', 'Irvine')
INSERT INTO dbo.Users VALUES (10082, 'Maha', 'Kabara', 'Doctor', 'Seattle')
INSERT INTO dbo.Users VALUES (10083, 'Aila', 'Hotaki', 'Engineer', 'Irvine')
INSERT INTO dbo.Users VALUES (10084, 'Alina', 'Kazzi', 'Teacher', 'San Diego')
INSERT INTO dbo.Users VALUES (10085, 'Ajlal', 'Nueimat', 'Architect', 'Seattle')
INSERT INTO dbo.Users VALUES (10086, 'Fadilah', 'Baz', 'Doctor', 'San Francisco')
INSERT INTO dbo.Users VALUES (10087, 'Gadi', 'Kuzbari', 'Engineer', 'Seattle')
INSERT INTO dbo.Users VALUES (10088, 'Rajab', 'Quraishi', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10089, 'Abdul-Wahhab', 'Maloof', 'Doctor', 'Seattle')
INSERT INTO dbo.Users VALUES (10090, 'Sama', 'Elnubi', 'Engineer', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10091, 'Shams Miseidani', 'Shams', 'Teacher', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10092, 'Lisha', 'Daher', 'Architect', 'San Francisco')
INSERT INTO dbo.Users VALUES (10093, 'Maliha', 'Shamoun', 'Doctor', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10094, 'Maisha', 'Bishara', 'Engineer', 'Tacoma')
INSERT INTO dbo.Users VALUES (10095, 'Wesam', 'Baraa', 'Architect', 'Seattle')
INSERT INTO dbo.Users VALUES (10096, 'Malika', 'Aswad', 'Doctor', 'San Diego')
INSERT INTO dbo.Users VALUES (10097, 'Ruwaidah', 'Fakhoury', 'Engineer', 'San Diego')
INSERT INTO dbo.Users VALUES (10098, 'Qamar', 'Mounir', 'Teacher', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10099, 'Noor', 'Wahdani', 'Architect', 'Los Angeles')
INSERT INTO dbo.Users VALUES (10100, 'Nihad', 'Samaha', 'Doctor', 'Los Angeles')